---
- id: snykio:go:github.com/hashicorp/vault-plugin-secrets-gcp/plugin:570192
  title: Improper Input Validation
  description: |
    [github.com/hashicorp/vault-plugin-secrets-gcp/plugin][1] is a backend
    plugin to be used with Hashicorp Vault.

    Affected versions of this package are vulnerable to Improper Input
    Validation. System TTLs were being used instead of the configured
    backend TTLs for dynamic service accounts. This could potentially lead
    to dangerous behaviour and deviates from best practices.



    [1]: https://github.com/hashicorp/vault-plugin-secrets-gcp
  affected_package: github.com/hashicorp/vault-plugin-secrets-gcp/plugin
  vulnerable_versions:
  - "<0.6.2"
  severity: medium
  package_manager: go
  cve:
  - CVE-2020-12757
  cwe:
  - CWE-20
  disclosed_date: 2020-05-22
  created_date: 2020-05-22
  last_modified_date: 2020-05-22
  credit:
  - Unknown
  references:
  - https://github.com/hashicorp/vault-plugin-secrets-gcp/commit/e43d20870c50f7428dead1411debcec075b35fb4
  - https://github.com/hashicorp/vault-plugin-secrets-gcp/pull/85
  - https://github.com/hashicorp/vault/blob/master/CHANGELOG.md
  source_url: https://snyk.io/vuln/SNYK-GOLANG-GITHUBCOMHASHICORPVAULTPLUGINSECRETSGCPPLUGIN-570192
