---
- id: snykio:packagist:nette/application:1015754
  title: Remote Code Execution (RCE)
  description: |
    [nette/application][1] is a full-stack component-based MVC kernel for
    PHP that helps you write powerful and modern web applications.

    Affected versions of this package are vulnerable to Remote Code
    Execution (RCE) by passing specially formed parameters to URL that may
    possibly leading to RCE.



    [1]: https://packagist.org/packages/nette/application
  affected_package: nette/application
  vulnerable_versions:
  - ">=2.2.0  <2.2.10"
  - ">=2.3.0  <2.3.14"
  - ">=2.4.0  <2.4.16"
  - ">=3.0.0  <3.0.6"
  severity: high
  package_manager: packagist
  cve:
  - CVE-2020-15227
  cwe:
  - CWE-74
  disclosed_date: 2020-10-02
  created_date: 2020-10-05
  last_modified_date: 2020-10-05
  credit:
  - Unknown
  references:
  - https://github.com/nette/application/security/advisories/GHSA-8gv3-3j7f-wg94
  source_url: https://snyk.io/vuln/SNYK-PHP-NETTEAPPLICATION-1015754
