---
- id: snykio:go:github.com/netlify/gotrue/api:1019459
  title: Information Exposure
  description: |
    [github.com/netlify/gotrue/api][1] is a SWT based API for managing users
    and issuing SWT tokens

    Affected versions of this package are vulnerable to Information
    Exposure. User enumeration is possible via the \"Log in\" widget. An
    authentication request with wrong credentials at the login panel returns
    the message “No user found with this email”.



    [1]: https://pkg.go.dev/github.com/netlify/gotrue/api
  affected_package: github.com/netlify/gotrue/api
  vulnerable_versions:
  - "*"
  severity: low
  package_manager: go
  cwe:
  - CWE-200
  disclosed_date: 2020-10-02
  created_date: 2020-11-22
  last_modified_date: 2020-11-22
  credit:
  - frontcraft
  references:
  - https://github.com/netlify/gotrue/commit/8db63ea448e82d3feae8fec45830edd3d7580f37
  - https://github.com/netlify/gotrue/pull/260
  - https://github.com/netlify/netlify-identity-widget/issues/225
  source_url: https://snyk.io/vuln/SNYK-GOLANG-GITHUBCOMNETLIFYGOTRUEAPI-1019459
