---
- id: ossindex:npm:product-monitor:2016-12-16
  title: Man in the Middle (MitM)
  description: "> product-monitor versions below 2.2.5 download JavaScript resources
    over HTTP, which leaves the module vulnerable to MITM attacks. \n> \n> -- [nodesecurity.io](https://nodesecurity.io/advisories/171)\n\n"
  affected_package: product-monitor
  vulnerable_versions:
  - "<2.2.5"
  package_manager: npm
  disclosed_date: 2016-12-16
  created_date: 2016-12-16
  last_modified_date: 2017-01-24
  credit:
  - OSSIndex
  references:
  - https://cwe.mitre.org/data/definitions/300.html
  - https://github.com/connected-web/product-monitor/commit/122122c605a235d5897590c0ef9d3682961707de
  - https://github.com/connected-web/product-monitor/issues/53
  - https://nodesecurity.io/advisories/171
  source_url: https://ossindex.net/resource/package/7014319864/vulnerabilities
- id: snykio:npm:product-monitor:CVE-2016-10567
  title: Resources Downloaded over Insecure Protocol
  description: |
    [`product-monitor`][1] is an HTML/JavaScript template for monitoring a
    product by encouraging product developers to gather all the information
    about the status of a product, including live monitoring, statistics,
    endpoints, and test results into one place. Affected versions of the
    package are vulnerable to Man in the Middle (MitM) attacks due to
    downloading resources over an insecure protocol.



    [1]: https://www.npmjs.com/package/product-monitor
  affected_package: product-monitor
  vulnerable_versions:
  - "<2.2.5"
  severity: high
  package_manager: npm
  cve:
  - CVE-2016-10567
  cwe:
  - CWE-319
  disclosed_date: 2016-11-04
  created_date: 2016-12-20
  last_modified_date: 2016-12-20
  credit:
  - Adam Baldwin
  references:
  - https://github.com/connected-web/product-monitor/commit/122122c605a235d5897590c0ef9d3682961707de
  - https://github.com/connected-web/product-monitor/issues/53
  source_url: https://snyk.io/vuln/npm:product-monitor:20161104
