---
- id: snykio:rubygems:application-config:566486
  title: Malicious Package
  description: |
    [application-config][1] is a malicious package.

    Affected versions of this package were found to be a Malicious Package,
    as it utilised typosquatting to run Malicious 3rd party scripts. It
    replaced genuine packages using an `_` and replaced it with `-` and vice
    versa



    [1]: https://rubygems.org/gems/application-config
  affected_package: application-config
  vulnerable_versions:
  - ">=0.0.0"
  severity: high
  package_manager: rubygems
  cwe:
  - CWE-506
  disclosed_date: 2020-04-17
  created_date: 2020-04-17
  last_modified_date: 2020-04-17
  credit:
  - Reversing Labs
  references:
  - https://thehackernews.com/2020/04/rubygem-typosquatting-malware.html
  source_url: https://snyk.io/vuln/SNYK-RUBY-APPLICATIONCONFIG-566486
