---
- id: snykio:rubygems:dependabot-omnibus:1040429
  title: Remote Code Execution (RCE)
  description: |
    [dependabot-omnibus][1] is an Automated dependency management

    Affected versions of this package are vulnerable to Remote Code
    Execution (RCE) by cloning source branch containing malicious injectable
    bash code.



    [1]: https://rubygems.org/gems/dependabot-omnibus
  affected_package: dependabot-omnibus
  vulnerable_versions:
  - ">=0.119.0.beta1  <0.125.1"
  severity: low
  package_manager: rubygems
  cve:
  - CVE-2020-26222
  cwe:
  - CWE-94
  disclosed_date: 2020-11-13
  created_date: 2020-11-15
  last_modified_date: 2020-11-15
  credit:
  - Unknown
  references:
  - https://github.com/dependabot/dependabot-core/pull/2727
  source_url: https://snyk.io/vuln/SNYK-RUBY-DEPENDABOTOMNIBUS-1040429
