---
- id: snykio:maven:com.liferay:com.liferay.portal.settings.authentication.ldap.web:585952
  title: Information Exposure
  description: |
    [com.liferay:com.liferay.portal.settings.authentication.ldap.web][1] is
    a settings authentication module for LifeRay.

    Affected versions of this package are vulnerable to Information
    Exposure. Liferay Portal allows remote attackers to obtain the LDAP
    server\'s password via the Test LDAP Connection feature.



    [1]: https://mvnrepository.com/artifact/com.liferay/com.liferay.portal.settings.authentication.ldap.web
  affected_package: com.liferay:com.liferay.portal.settings.authentication.ldap.web
  vulnerable_versions:
  - "< 3.0.23"
  - ">= 4.0.1 < 4.0.9"
  severity: high
  package_manager: maven
  cve:
  - CVE-2020-15841
  cwe:
  - CWE-200
  disclosed_date: 2020-07-20
  created_date: 2020-07-20
  last_modified_date: 2020-07-20
  credit:
  - Unknown
  references:
  - https://github.com/community-security-team/liferay-portal/compare/7.2.1-ga2...7.2.1-cumulative
  - https://issues.liferay.com/browse/LPE-16928
  - https://portal.liferay.dev/learn/security/known-vulnerabilities/-/asset_publisher/HbL5mxmVrnXW/content/id/119317439
  source_url: https://snyk.io/vuln/SNYK-JAVA-COMLIFERAY-585952
