---
- id: snykio:maven:com.alibaba.nacos:nacos-config:1059091
  title: Improper Authentication
  description: |+
    Affected versions of this package are vulnerable to Improper
    Authentication. When nacos is deployed in the default configuration, the
    administrator dashboard can be accessed without authentication. This can
    be leveraged to execute arbitrary SQL queries, which leads to the
    disclosure of sensitive information.

  affected_package: com.alibaba.nacos:nacos-config
  vulnerable_versions:
  - ">= 0"
  severity: high
  package_manager: maven
  cwe:
  - CWE-287
  disclosed_date: 2020-12-12
  created_date: 2021-01-12
  last_modified_date: 2021-01-12
  credit:
  - threedr3am
  references:
  - https://github.com/alibaba/nacos/issues/4463
  - https://github.com/alibaba/nacos/pull/4517
  source_url: https://snyk.io/vuln/SNYK-JAVA-COMALIBABANACOS-1059091
