---
- id: snykio:maven:io.smallrye.config:smallrye-config:548898
  title: Information Exposure
  description: |
    [io.smallrye.config:smallrye-config][1] is a SmallRye implementation of
    Eclipse MicroProfile Config

    Affected versions of this package are vulnerable to Information
    Exposure. The API can allow other code running within the application
    server to potentially obtain the ClassLoader, bypassing any permissions
    checks that should have been applied. The largest threat from this
    vulnerability is a threat to data confidentiality.



    [1]: https://github.com/smallrye/smallrye-config
  affected_package: io.smallrye.config:smallrye-config
  vulnerable_versions:
  - "< 1.6.2"
  severity: medium
  package_manager: maven
  cve:
  - CVE-2020-1729
  cwe:
  - CWE-863
  disclosed_date: 2020-02-13
  created_date: 2020-02-17
  last_modified_date: 2020-02-17
  credit:
  - Unknown
  references:
  - https://bugzilla.redhat.com/show_bug.cgi?id=1802444
  - https://github.com/smallrye/smallrye-config/commit/fb0def6f61c09a2a80c9145e4ec6521225cd0b99
  source_url: https://snyk.io/vuln/SNYK-JAVA-IOSMALLRYECONFIG-548898
