---
- id: snykio:maven:io.springfox:springfox-swagger-ui:674160
  title: Improper Input Validation
  description: |
    [io.springfox:springfox-swagger-ui][1] is an Automated JSON API
    documentation for API\'s built with Spring

    Affected versions of this package are vulnerable to Improper Input
    Validation. The input to the `/api-docs?group=` URL query parameter is
    untrusted input and is not encoded before being written to the log.



    [1]: https://github.com/springfox/springfox
  affected_package: io.springfox:springfox-swagger-ui
  vulnerable_versions:
  - ">= 0"
  severity: medium
  package_manager: maven
  cwe:
  - CWE-20
  disclosed_date: 2020-09-09
  created_date: 2020-11-16
  last_modified_date: 2020-11-16
  credit:
  - jackatsw
  references:
  - https://github.com/springfox/springfox/pull/3549
  source_url: https://snyk.io/vuln/SNYK-JAVA-IOSPRINGFOX-674160
