---
- id: snykio:maven:org.apache.druid.extensions:druid-basic-security:564257
  title: LDAP Injection
  description: |
    [org.apache.druid.extensions:druid-basic-security][1] is a basic
    security package for Apache Druid.

    Affected versions of this package are vulnerable to LDAP Injection. When
    LDAP authentication is enabled in Apache Druid, callers of Druid APIs
    with a valid set of LDAP credentials can bypass the
    `credentialsValidator.userSearch` filter barrier that determines if a
    valid LDAP user is allowed to authenticate with Druid.



    [1]: https://druid.apache.org/
  affected_package: org.apache.druid.extensions:druid-basic-security
  vulnerable_versions:
  - ">= 0.17.0 < 0.17.1"
  severity: high
  package_manager: maven
  cve:
  - CVE-2020-1958
  cwe:
  - CWE-90
  disclosed_date: 2020-04-01
  created_date: 2020-04-01
  last_modified_date: 2020-04-01
  credit:
  - Unknown
  references:
  - https://github.com/apache/druid/commit/dbaabdd24710fef726c5730c609937706f456a44
  - https://lists.apache.org/thread.html/r9d437371793b410f8a8e18f556d52d4bb68e18c537962f6a97f4945e%40%3Cdev.druid.apache.org%3E
  source_url: https://snyk.io/vuln/SNYK-JAVA-ORGAPACHEDRUIDEXTENSIONS-564257
