---
- id: snykio:maven:org.openapitools:openapi-generator-project:174513
  title: Man-in-the-Middle (MitM)
  description: |
    [org.openapitools:openapi-generator-project][1] is an is a package that
    allows generation of API client libraries (SDK generation), server
    stubs, documentation and configuration automatically given an OpenAPI
    Spec (v2, v3).

    Affected versions of this package are vulnerable to Man-in-the-Middle
    (MitM). The resolving process of `build.gradle`,
    `build.gradle.mustache`, and `build.sbt` files are conducted over HTTP
    instead of HTTPS. Any of these dependent artifacts could be compromised
    by a MITM attack.



    [1]: https://openapi-generator.tech
  affected_package: org.openapitools:openapi-generator-project
  vulnerable_versions:
  - ">= 3.0.0 < 4.0.0-beta3"
  severity: medium
  package_manager: maven
  cve:
  - CVE-2019-11405
  cwe:
  - CWE-300
  disclosed_date: 2019-04-21
  created_date: 2019-04-21
  last_modified_date: 2019-04-21
  credit:
  - JLLeitschuh
  references:
  - https://github.com/OpenAPITools/openapi-generator/commit/076ba9e09afd1d78aeed9448eb2a103fe1d9b3b4
  - https://github.com/OpenAPITools/openapi-generator/issues/2253
  - https://github.com/OpenAPITools/openapi-generator/pull/2248
  source_url: https://snyk.io/vuln/SNYK-JAVA-ORGOPENAPITOOLS-174513
