---
- id: snykio:maven:org.apache.karaf.config:org.apache.karaf.config.core:174625
  title: Directory Traversal
  description: |
    [org.apache.karaf.config:org.apache.karaf.config.core][1] is a bundle
    that provides Karaf services.

    Affected versions of this package are vulnerable to Directory Traversal.
    The Apache Karaf Config component provides an install method that can be
    used to traverse in any directory and overwrite existing files within an
    application. The condition of this vulnerability being exploited is
    considered low if the permissions of Karaf process has limited
    permission on the file system.



    [1]: https://karaf.apache.org
    \nA Directory Traversal attack (also known as path traversal) aims to
    access files and directories that are stored outside the intended
    folder. By manipulating files with \"dot-dot-slash (../)\" sequences and
    its variations, or by using absolute file paths, it may be possible to
    access arbitrary files and directories stored on file system, including
    application source code, configuration, and other critical system files.

    Directory Traversal vulnerabilities can be generally divided into two
    types:

    * **Information Disclosure**\: Allows the attacker to gain information
      about the folder structure or read the contents of sensitive files on
      the system.

    `st` is a module for serving static files on web pages, and contains a
    [vulnerability of this type][1]. In our example, we will serve files
    from the `public` route.

    If an attacker requests the following URL from our server, it will in
    turn leak the sensitive private key of the root user.

        curl http://localhost:8080/public/%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/root/.ssh/id_rsa

    **Note** `%2e` is the URL encoded version of `.` (dot).

    * **Writing arbitrary files**\: Allows the attacker to create or replace
      existing files. This type of vulnerability is also known as
      `Zip-Slip`.

    One way to achieve this is by using a malicious `zip` archive that holds
    path traversal filenames. When each filename in the zip archive gets
    concatenated to the target extraction folder, without validation, the
    final path ends up outside of the target folder. If an executable or a
    configuration file is overwritten with a file containing malicious code,
    the problem can turn into an arbitrary code execution issue quite
    easily.

    The following is an example of a `zip` archive with one benign file and
    one malicious file. Extracting the malicious file will result in
    traversing out of the target folder, ending up in `/root/.ssh/`
    overwriting the `authorized_keys` file:

        2018-04-15 22:04:29 .....           19           19  good.txt
        2018-04-15 22:04:42 .....           20           20  ../../../../../../root/.ssh/authorized_keys



    [1]: https://snyk.io/vuln/npm:st:20140206
  affected_package: org.apache.karaf.config:org.apache.karaf.config.core
  vulnerable_versions:
  - "< 4.2.5"
  severity: medium
  package_manager: maven
  cve:
  - CVE-2019-0226
  cwe:
  - CWE-22
  disclosed_date: 2019-05-06
  created_date: 2019-05-09
  last_modified_date: 2019-05-09
  credit:
  - Ma Lingtao
  references:
  - https://github.com/apache/karaf/commit/fe3bc4108e5a8b3c804e5da91ec0d5695588eb25
  - https://github.com/apache/karaf/pull/805
  - https://lists.apache.org/thread.html/1baa6f1df0e95fb1cd679067117354af2ab4423277d9a0ff6e8bf790@%3Cdev.karaf.apache.org%3E
  source_url: https://snyk.io/vuln/SNYK-JAVA-ORGAPACHEKARAFCONFIG-174625
