---
- id: snykio:maven:org.jenkins-ci.plugins:storable-configs-plugin:728011
  title: Arbitrary File Write
  description: |+
    Affected versions of this package are vulnerable to Arbitrary File Write
    it does not restrict the user-specified file name.

  affected_package: org.jenkins-ci.plugins:storable-configs-plugin
  vulnerable_versions:
  - ">= 0"
  severity: medium
  package_manager: maven
  cve:
  - CVE-2020-2278
  cwe:
  - CWE-98
  disclosed_date: 2020-09-17
  created_date: 2020-09-17
  last_modified_date: 2020-09-17
  credit:
  - CloudBees
  - Daniel Beck
  - Inc.
  references:
  - https://www.jenkins.io/security/advisory/2020-09-16/#SECURITY-1968
  source_url: https://snyk.io/vuln/SNYK-JAVA-ORGJENKINSCIPLUGINS-728011
- id: snykio:maven:org.jenkins-ci.plugins:storable-configs-plugin:728012
  title: Arbitrary File Write
  description: |+
    Affected versions of this package are vulnerable to Arbitrary File Write
    it does not restrict the user-specified file name.

  affected_package: org.jenkins-ci.plugins:storable-configs-plugin
  vulnerable_versions:
  - ">= 0"
  severity: medium
  package_manager: maven
  cve:
  - CVE-2020-2278
  cwe:
  - CWE-98
  disclosed_date: 2020-09-17
  created_date: 2020-09-17
  last_modified_date: 2020-09-17
  credit:
  - CloudBees
  - Daniel Beck
  - Inc.
  references:
  - https://www.jenkins.io/security/advisory/2020-09-16/#SECURITY-1968
  source_url: https://snyk.io/vuln/SNYK-JAVA-ORGJENKINSCIPLUGINS-728012
- id: snykio:maven:org.jenkins-ci.plugins:storable-configs-plugin:728013
  title: Arbitrary File Read
  description: |+
    Affected versions of this package are vulnerable to Arbitrary File Read.
    It allows users with Job/Read permission to read arbitrary files on the
    Jenkins controller.

  affected_package: org.jenkins-ci.plugins:storable-configs-plugin
  vulnerable_versions:
  - ">= 0"
  severity: medium
  package_manager: maven
  cve:
  - CVE-2020-2277
  cwe:
  - CWE-22
  disclosed_date: 2020-09-17
  created_date: 2020-09-17
  last_modified_date: 2020-09-17
  credit:
  - CloudBees
  - Daniel Beck
  - Inc.
  references:
  - https://www.jenkins.io/security/advisory/2020-09-16/#SECURITY-1968
  source_url: https://snyk.io/vuln/SNYK-JAVA-ORGJENKINSCIPLUGINS-728013
