---
- id: snykio:go:github.com/mattermost/mattermost-server/app:572865
  title: Information Exposure
  description: |
    [github.com/mattermost/mattermost-server/app][1] is an open source
    Slack-alternative in Golang and React.

    Affected versions of this package are vulnerable to Information
    Exposure. Non-members can receive broadcasted team details via the
    `update_team` WebSocket event.



    [1]: https://github.com/mattermost/mattermost-server
  affected_package: github.com/mattermost/mattermost-server/app
  vulnerable_versions:
  - "<5.20.0"
  severity: medium
  package_manager: go
  cve:
  - CVE-2020-14457
  cwe:
  - CWE-200
  disclosed_date: 2020-06-19
  created_date: 2020-06-19
  last_modified_date: 2020-06-19
  credit:
  - Unknown
  references:
  - https://github.com/mattermost/mattermost-server/commit/d0b87544987ad72ec17c7b
  - https://mattermost.com/security-updates/
  source_url: https://snyk.io/vuln/SNYK-GOLANG-GITHUBCOMMATTERMOSTMATTERMOSTSERVERAPP-572865
- id: snykio:go:github.com/mattermost/mattermost-server/app:572884
  title: Denial of Service (DoS)
  description: |+
    [github.com/mattermost/mattermost-server/app][1] is an open source
    Slack-alternative in Golang and React.

    Affected versions of this package are vulnerable to Denial of Service
    (DoS). A large Slack import could cause the server to run out of memory.



    [1]: https://github.com/mattermost/mattermost-server
    \nDenial of Service (DoS) describes a family of attacks, all aimed at
    making a system inaccessible to its intended and legitimate users.

    Unlike other vulnerabilities, DoS attacks usually do not aim at
    breaching security. Rather, they are focused on making websites and
    services unavailable to genuine users resulting in downtime.

    One popular Denial of Service vulnerability is DDoS (a Distributed
    Denial of Service), an attack that attempts to clog network pipes to the
    system by generating a large volume of traffic from many machines.

    When it comes to open source libraries, DoS vulnerabilities allow
    attackers to trigger such a crash or crippling of the service by using a
    flaw either in the application code or from the use of open source
    libraries.

    Two common types of DoS vulnerabilities:

    * High CPU/Memory Consumption- An attacker sending crafted requests that
      could cause the system to take a disproportionate amount of time to
      process. For example,
      [commons-fileupload:commons-fileupload](SNYK-JAVA-COMMONSFILEUPLOAD-30082).

    * Crash - An attacker sending crafted requests that could cause the
      system to crash. For Example, [npm `ws` package](npm:ws:20171108)

  affected_package: github.com/mattermost/mattermost-server/app
  vulnerable_versions:
  - "<5.18.0"
  severity: medium
  package_manager: go
  cve:
  - CVE-2019-20845
  cwe:
  - CWE-400
  disclosed_date: 2020-06-20
  created_date: 2020-06-20
  last_modified_date: 2020-06-20
  credit:
  - Abhisek Datta
  references:
  - https://github.com/mattermost/mattermost-server/commit/88cbd77fea20a48698391c4864eb2643ba39cc37
  - https://mattermost.com/security-updates/
  source_url: https://snyk.io/vuln/SNYK-GOLANG-GITHUBCOMMATTERMOSTMATTERMOSTSERVERAPP-572884
