---
- id: snykio:go:github.com/mattermost/mattermost-server/config:572882
  title: Insecure Permissions
  description: |
    [github.com/mattermost/mattermost-server/config][1] is an open source
    Slack-alternative in Golang and React.

    Affected versions of this package are vulnerable to Insecure
    Permissions. Configuration files are being assigned unnecessarily
    permissive modes, potentially enabling privilege escalation.



    [1]: https://github.com/mattermost/mattermost-server
  affected_package: github.com/mattermost/mattermost-server/config
  vulnerable_versions:
  - "<5.9.7"
  - ">=5.15.0 <5.15.4"
  - ">=5.16.0 <5.16.4"
  - ">=5.17.0 <5.17.2"
  severity: medium
  package_manager: go
  cve:
  - CVE-2019-20843
  cwe:
  - CWE-275
  disclosed_date: 2020-06-20
  created_date: 2020-06-20
  last_modified_date: 2020-06-20
  credit:
  - Juho Nurminen
  references:
  - https://github.com/mattermost/mattermost-server/commit/50fad5b621d8f8f9cf762c74f2080eae4689a29a
  - https://github.com/mattermost/mattermost-server/commit/bb8a7650a884e1f012fb3cfd094b48bceb5d1b5d
  - https://github.com/mattermost/mattermost-server/commit/cdbca7ab48303233a43f55523d3884e1db73bb85
  - https://mattermost.com/security-updates/
  source_url: https://snyk.io/vuln/SNYK-GOLANG-GITHUBCOMMATTERMOSTMATTERMOSTSERVERCONFIG-572882
- id: snykio:go:github.com/mattermost/mattermost-server/config:572885
  title: Improper Access Control
  description: |
    [github.com/mattermost/mattermost-server/config][1] is an open source
    Slack-alternative in Golang and React.

    Affected versions of this package are vulnerable to Improper Access
    Control. Server-local file storage was assigning unnecessarily
    permissive modes to files and directories.



    [1]: https://github.com/mattermost/mattermost-server
  affected_package: github.com/mattermost/mattermost-server/config
  vulnerable_versions:
  - "<5.18.0"
  severity: medium
  package_manager: go
  cve:
  - CVE-2019-20846
  cwe:
  - CWE-284
  disclosed_date: 2020-06-20
  created_date: 2020-06-20
  last_modified_date: 2020-06-20
  credit:
  - Juho Nurminen
  references:
  - https://github.com/mattermost/mattermost-server/commit/cd38d63bf448ae791f252c3704a705e94b26959f
  - https://mattermost.com/security-updates/
  source_url: https://snyk.io/vuln/SNYK-GOLANG-GITHUBCOMMATTERMOSTMATTERMOSTSERVERCONFIG-572885
