---
- id: npmjs:npm:@wturyn/swagger-injector:1173
  title: Path Traversal
  description: All versions of `@wturyn/swagger-injector` are vulnerable to Path Traversal.
    The package fails to sanitize URLs, allowing attackers to access server files
    outside of the configured `dist` folder using relative paths.
  affected_package: "@wturyn/swagger-injector"
  vulnerable_versions:
  - ">=0.0.0"
  severity: high
  package_manager: npm
  cwe: CWE-22
  disclosed_date: 1970-01-01
  created_date: 1970-01-01
  last_modified_date: 1970-01-01
  credit: Iuri de Silvio
