---
- id: snykio:go:github.com/containous/traefik/:575248
  title: Improper Authentication
  description: |
    [github.com/containous/traefik/][1] is an a modern HTTP reverse proxy
    and load balancer that makes deploying microservices easy.

    Affected versions of this package are vulnerable to Improper
    Authentication. In certain configurations, allows `HTTPS sessions` to
    proceed without mutual TLS verification in a situation where
    `ERR_BAD_SSL_CLIENT_AUTH_CERT` should have occurred.



    [1]: https://traefik.io/
  affected_package: github.com/containous/traefik/
  vulnerable_versions:
  - "*"
  severity: medium
  package_manager: go
  cve:
  - CVE-2019-20894
  cwe:
  - CWE-287
  disclosed_date: 2020-07-03
  created_date: 2020-07-03
  last_modified_date: 2020-07-03
  credit:
  - tomfun
  references:
  - https://github.com/containous/traefik/issues/5312
  source_url: https://snyk.io/vuln/SNYK-GOLANG-GITHUBCOMCONTAINOUSTRAEFIK-575248
