---
- id: friendsofphp:packagist:illuminate/database:2014-05-20
  title: Risk of mass-assignment vulnerabilities
  affected_package: illuminate/database
  vulnerable_versions:
  - ">=4.0.0 <4.0.99"
  - ">=4.1.0 <4.1.29"
  package_manager: packagist
  disclosed_date: 2014-05-20
  created_date: 2014-05-20
  last_modified_date: 2014-05-20
  credit:
  - FriendsOfPHP
  references:
  - https://laravel.com/docs/5.1/upgrade#upgrade-4.1.29
  source_url: https://github.com/FriendsOfPHP/security-advisories/blob/master/illuminate/database/2014-05-20.yaml
- id: ossindex:packagist:illuminate/database:8399183260
  title: Risk of mass-assignment vulnerabilities
  description: Risk of mass-assignment vulnerabilities
  affected_package: illuminate/database
  vulnerable_versions:
  - ">=4.0.0 <4.0.99"
  - ">=4.1.0 <4.1.29"
  package_manager: packagist
  disclosed_date: 2016-06-05
  created_date: 2016-06-05
  last_modified_date: 2016-06-05
  credit:
  - OSSIndex
  references:
  - http://laravel.com/docs/upgrade#upgrade-4.1.29
  - https://github.com/FriendsOfPHP/security-advisories/blob/master/illuminate/database/2014-05-20.yaml
  source_url: https://ossindex.net/resource/package/8397375826/vulnerabilities
- id: snykio:packagist:illuminate/database:597623
  title: Improper Input Validation
  description: |+
    Affected versions of this package are vulnerable to Improper Input
    Validation via mass assignment of Eloquent attributes that includes the
    model\'s table name.

  affected_package: illuminate/database
  vulnerable_versions:
  - "<6.18.34"
  - ">=7.0.0  <7.23.2"
  severity: high
  package_manager: packagist
  cwe:
  - CWE-20
  disclosed_date: 2020-08-09
  created_date: 2020-08-09
  last_modified_date: 2020-08-09
  credit:
  - Unknown
  references:
  - https://blog.laravel.com/security-release-laravel-61834-7232
  - https://github.com/illuminate/database/commit/260dc0a2d75cf66118ffdec936f505e938221077
  source_url: https://snyk.io/vuln/SNYK-PHP-ILLUMINATEDATABASE-597623
- id: snykio:packagist:illuminate/database:597625
  title: Improper Input Validation
  description: |+
    Affected versions of this package are vulnerable to Improper Input
    Validation via mass assignment of Eloquent attributes that includes the
    model\'s table name.

  affected_package: illuminate/database
  vulnerable_versions:
  - "<6.18.34"
  - ">=7.0.0  <7.23.2"
  severity: high
  package_manager: packagist
  cwe:
  - CWE-20
  disclosed_date: 2020-08-09
  created_date: 2020-08-09
  last_modified_date: 2020-08-09
  credit:
  - Unknown
  references:
  - https://blog.laravel.com/security-release-laravel-61834-7232
  - https://github.com/illuminate/database/commit/260dc0a2d75cf66118ffdec936f505e938221077
  source_url: https://snyk.io/vuln/SNYK-PHP-ILLUMINATEDATABASE-597625
- id: snykio:packagist:illuminate/database:70106
  title: Mass Assignment
  description: |
    Affected versions of [`illuminate/database`][1] are vulnerable to Mass
    Assignment vulnerabilities.



    [1]: https://packagist.org/packages/illuminate/database
  affected_package: illuminate/database
  vulnerable_versions:
  - ">=4  <4.1.29"
  severity: medium
  package_manager: packagist
  cwe:
  - CWE-915
  disclosed_date: 2014-05-20
  created_date: 2014-05-20
  last_modified_date: 2014-05-20
  credit:
  - Unknown
  references:
  - https://laravel.com/docs/5.1/upgrade#upgrade-4.1.29
  source_url: https://snyk.io/vuln/SNYK-PHP-ILLUMINATEDATABASE-70106
