---
- id: snykio:go:github.com/hashicorp/consul/agent/config:560767
  title: Cryptographic Issues
  description: |
    [github.com/hashicorp/consul/agent/config][1] is a package, part of
    Hashicorps, consul.

    Affected versions of this package are vulnerable to Cryptographic
    Issues. 3DES ciphers could be abused by a network attacker who can
    monitor a long-lived Triple-DES HTTPS connection and recover sensitive
    information.



    [1]: https://github.com/hashicorp/consul
  affected_package: github.com/hashicorp/consul/agent/config
  vulnerable_versions:
  - "<1.7.2"
  severity: medium
  package_manager: go
  cwe:
  - CWE-310
  disclosed_date: 2020-03-19
  created_date: 2020-03-19
  last_modified_date: 2020-03-19
  credit:
  - Unknown
  references:
  - https://github.com/hashicorp/consul/commit/7777891aa6e8052c97d457b2b648a3111eb8fb10
  source_url: https://snyk.io/vuln/SNYK-GOLANG-GITHUBCOMHASHICORPCONSULAGENTCONFIG-560767
