---
- id: snykio:pypi:anyconfig:1055467
  title: Security Bypass
  description: |
    [anyconfig][1] is a Library provides common APIs to load and dump
    configuration files in various formats

    Affected versions of this package are vulnerable to Security Bypass. The
    `ac_safe` argument is processed incorrectly.



    [1]: https://pypi.org/project/anyconfig
  affected_package: anyconfig
  vulnerable_versions:
  - "< 0.10.0"
  severity: high
  package_manager: pypi
  cwe:
  - CWE-358
  disclosed_date: 2021-01-05
  created_date: 2021-01-05
  last_modified_date: 2021-01-05
  credit:
  - danielkorczak
  references:
  - https://github.com/ssato/python-anyconfig/commit/4ab8770972fbd689d7152e572380fa9fbe88df05
  - https://github.com/ssato/python-anyconfig/issues/118#issuecomment-753284295
  source_url: https://snyk.io/vuln/SNYK-PYTHON-ANYCONFIG-1055467
