---
- id: snykio:pypi:codecov:552149
  title: Command Injection
  description: |
    [codecov][1] is a Python report uploader for Codecov.

    Affected versions of this package are vulnerable to Command Injection.
    The vulnerability occurs due to not sanitizing `gcov` arguments before
    being being provided to the `popen` method.

    ### PoC by Snyk   {#poc-by-snyk}

        codecov --gcov-args='& echo test > vuln1.txt' --gcov-exec='& echo test > vuln2.txt' --gcov-root='& echo test > vuln3.txt' -t foobar



    [1]: https://pypi.org/project/codecov
  affected_package: codecov
  vulnerable_versions:
  - "< 2.0.16"
  severity: medium
  package_manager: pypi
  cve:
  - CVE-2019-10800
  cwe:
  - CWE-78
  disclosed_date: 2020-02-25
  created_date: 2020-02-25
  last_modified_date: 2020-02-25
  credit:
  - Snyk Security Team
  references:
  - https://github.com/codecov/codecov-python/commit/2a80aa434f74feb31242b6f213b75ce63ae97902
  source_url: https://snyk.io/vuln/SNYK-PYTHON-CODECOV-552149
