---
- id: snykio:pypi:openapi-python-client:598766
  title: Directory Traversal
  description: |
    [openapi-python-client][1] is a package that generates modern Python
    clients from OpenAPI.

    Affected versions of this package are vulnerable to Directory Traversal
    via a maliciously crafted OpenAPI document.



    [1]: https://www.pypi.org/project/openapi-python-client
    \nA Directory Traversal attack (also known as path traversal) aims to
    access files and directories that are stored outside the intended
    folder. By manipulating files with \"dot-dot-slash (../)\" sequences and
    its variations, or by using absolute file paths, it may be possible to
    access arbitrary files and directories stored on file system, including
    application source code, configuration, and other critical system files.

    Directory Traversal vulnerabilities can be generally divided into two
    types:

    * **Information Disclosure**\: Allows the attacker to gain information
      about the folder structure or read the contents of sensitive files on
      the system.

    `st` is a module for serving static files on web pages, and contains a
    [vulnerability of this type][1]. In our example, we will serve files
    from the `public` route.

    If an attacker requests the following URL from our server, it will in
    turn leak the sensitive private key of the root user.

        curl http://localhost:8080/public/%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/root/.ssh/id_rsa

    **Note** `%2e` is the URL encoded version of `.` (dot).

    * **Writing arbitrary files**\: Allows the attacker to create or replace
      existing files. This type of vulnerability is also known as
      `Zip-Slip`.

    One way to achieve this is by using a malicious `zip` archive that holds
    path traversal filenames. When each filename in the zip archive gets
    concatenated to the target extraction folder, without validation, the
    final path ends up outside of the target folder. If an executable or a
    configuration file is overwritten with a file containing malicious code,
    the problem can turn into an arbitrary code execution issue quite
    easily.

    The following is an example of a `zip` archive with one benign file and
    one malicious file. Extracting the malicious file will result in
    traversing out of the target folder, ending up in `/root/.ssh/`
    overwriting the `authorized_keys` file:

        2018-04-15 22:04:29 .....           19           19  good.txt
        2018-04-15 22:04:42 .....           20           20  ../../../../../../root/.ssh/authorized_keys



    [1]: https://snyk.io/vuln/npm:st:20140206
  affected_package: openapi-python-client
  vulnerable_versions:
  - "< 0.5.3"
  severity: low
  package_manager: pypi
  cve:
  - CVE-2020-15141
  cwe:
  - CWE-22
  disclosed_date: 2020-08-16
  created_date: 2020-08-16
  last_modified_date: 2020-08-16
  credit:
  - Unknown
  references:
  - https://github.com/triaxtec/openapi-python-client/blob/main/CHANGELOG.md#053---2020-08-13
  - https://github.com/triaxtec/openapi-python-client/commit/3e7dfae5d0b3685abf1ede1bc6c086a116ac4746
  source_url: https://snyk.io/vuln/SNYK-PYTHON-OPENAPIPYTHONCLIENT-598766
- id: snykio:pypi:openapi-python-client:608080
  title: Arbitrary Code Execution
  description: |
    [openapi-python-client][1] is a package that generates modern Python
    clients from OpenAPI.

    Affected versions of this package are vulnerable to Arbitrary Code
    Execution. Clients generated with a maliciously crafted OpenAPI Document
    can generate arbitrary Python code. Subsequent execution of this
    malicious client leads to arbitrary code execution.



    [1]: https://www.pypi.org/project/openapi-python-client
  affected_package: openapi-python-client
  vulnerable_versions:
  - "< 0.5.3"
  severity: high
  package_manager: pypi
  cve:
  - CVE-2020-15142
  cwe:
  - CWE-94
  disclosed_date: 2020-08-20
  created_date: 2020-08-21
  last_modified_date: 2020-08-21
  credit:
  - Daniel GrossmannKavanagh
  - Dylan Anthony
  - Ethan Mann
  references:
  - https://github.com/triaxtec/openapi-python-client/security/advisories/GHSA-9x4c-63pf-525f
  source_url: https://snyk.io/vuln/SNYK-PYTHON-OPENAPIPYTHONCLIENT-608080
