---
- id: snykio:go:k8s.io/kubernetes/staging/src/k8s.io/client-go/transport:1018856
  title: Improper Output Neutralization for Logs
  description: |+
    Affected versions of this package are vulnerable to Improper Output
    Neutralization for Logs. Incomplete fix for `CVE-2019-11250` allows for
    token leak in logs when `logLevel` &gt;= 9

  affected_package: k8s.io/kubernetes/staging/src/k8s.io/client-go/transport
  vulnerable_versions:
  - "<1.20.0-alpha.2"
  severity: medium
  package_manager: go
  cve:
  - CVE-2020-8565
  cwe:
  - CWE-117
  disclosed_date: 2020-10-14
  created_date: 2020-10-16
  last_modified_date: 2020-10-16
  credit:
  - Unknown
  references:
  - https://bugzilla.redhat.com/show_bug.cgi?id=1886638
  - https://github.com/kubernetes/kubernetes/issues/95623
  - https://github.com/kubernetes/kubernetes/pull/95316
  - https://github.com/kubernetes/kubernetes/pull/95316/commits/f0f52255412cbc6834bd225a59608ebb4a0d399b
  - https://groups.google.com/g/kubernetes-announce/c/ScdmyORnPDk
  source_url: https://snyk.io/vuln/SNYK-GOLANG-K8SIOKUBERNETESSTAGINGSRCK8SIOCLIENTGOTRANSPORT-1018856
